/* eslint-disable */
import * as Types from '../graphql/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type CreateCheckpointMutationVariables = Types.Exact<{
  eventId: Types.Scalars['Int']['input'];
  cpId: Types.Scalars['Int']['input'];
  cpCode: Types.InputMaybe<Types.Scalars['String']['input']>;
  skipped: Types.InputMaybe<Types.Scalars['Boolean']['input']>;
  skipReason: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;


export type CreateCheckpointMutation = { __typename?: 'Mutation', createCheckpoint: { __typename?: 'CreateCheckpointResult', checkpoint: { __typename?: 'Checkpoint', id: number, event_id: number, cp_id: number, cp_code: string | null, skipped: boolean, skip_reason: string | null, created_at: string, updated_at: string } | null } };


export const CreateCheckpointDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateCheckpoint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"eventId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"cpId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"cpCode"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"skipped"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Boolean"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"skipReason"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createCheckpoint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"event_id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"eventId"}}},{"kind":"Argument","name":{"kind":"Name","value":"cp_id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"cpId"}}},{"kind":"Argument","name":{"kind":"Name","value":"cp_code"},"value":{"kind":"Variable","name":{"kind":"Name","value":"cpCode"}}},{"kind":"Argument","name":{"kind":"Name","value":"skipped"},"value":{"kind":"Variable","name":{"kind":"Name","value":"skipped"}}},{"kind":"Argument","name":{"kind":"Name","value":"skip_reason"},"value":{"kind":"Variable","name":{"kind":"Name","value":"skipReason"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"checkpoint"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"event_id"}},{"kind":"Field","name":{"kind":"Name","value":"cp_id"}},{"kind":"Field","name":{"kind":"Name","value":"cp_code"}},{"kind":"Field","name":{"kind":"Name","value":"skipped"}},{"kind":"Field","name":{"kind":"Name","value":"skip_reason"}},{"kind":"Field","name":{"kind":"Name","value":"created_at"}},{"kind":"Field","name":{"kind":"Name","value":"updated_at"}}]}}]}}]}}]} as unknown as DocumentNode<CreateCheckpointMutation, CreateCheckpointMutationVariables>;