module.exports = {
  events: require("./events"),
  event: require("./event"),
  checkpoints: require("./checkpoints"),
  createEvent: require("./createEvent"),
  deleteEvent: require("./deleteEvent"),
  createCheckpoint: require("./createCheckpoint"),
  createVirtualChallenge: require("./createVirtualChallenge"),
  enrollVirtualChallenge: require("./enrollVirtualChallenge"),
  friends: require('./friends'),
  inviteToEvent: require("./inviteToEvent"),
  joinEvent: require("./joinEvent"),
  deleteCheckpoint: require("./deleteCheckpoint"),
  participants: require("./participants"),
  pointsNearby: require("./pointsNearby"),
  virtualChallenges: require("./virtualChallenges"),
  virtualChallenge: require("./virtualChallenge"),
  checkInVirtualCheckpoint: require("./checkInVirtualCheckpoint"),
  signIn: require("./signIn"),
};
