name: Deployment

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
jobs:
  update_gh_pages:
    name: 'Update github pages'
    runs-on: ubuntu-latest

    steps:
      - name: Download build folder
        uses: actions/download-artifact@v1
        with:
          name: client-dist
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
